name: CI Branch 6.0

on:
  push:
    branches:
      - '6.0'
  pull_request:
    branches:
      - '6.0'
  workflow_dispatch:

jobs:
  testsuite:
    name: "Test Suite"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: [ '8.0.2', '8.1' ]
        symfony-version: [ '6.0', '6.1' ]
    steps:
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          #extensions: json, libxml, pdo, pdo_mysql, pdo_sqlite, pdo_pgsql, sqlite3
          coverage: pcov

      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.MY_PAT }}

      - name: Composer get cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Composer cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Composer update (Symfony version ${{ matrix.symfony-version }})
        run: composer install --prefer-dist --no-interaction

      - name: Run tests
        run: vendor/bin/phpunit --verbose --coverage-clover=Tests/coverage.xml

      - name: Code Coverage Report
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: Tests/coverage.xml
          fail_ci_if_error: true
          verbose: true
